### ISSUE TITLE
[BUG]: async_setup_platforms obsoleted

### ISSUE THREAD

**Issue by DarthLowen** [CoMPaTech/stromer#10]
### Describe the bug.

The following warning was logged:

```
Logger: homeassistant.helpers.frame Source: helpers/frame.py:77 First occurred: 8:31:45 PM (1 occurrences) Last logged: 8:31:45 PM
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for stromer using this method at custom_components/stromer/__init__.py, line 56: hass.config_entries.async_setup_platforms(entry, PLATFORMS)
```

I've had some issues getting the integration to configure, however after a reload it suddenly found my bike and set up the sensors. Not sure if it's related to this WARNING message though.

Thanks for this integration btw!

### What version of Home Assistant Core has the issue?

2023.3.1

### What type of installation are you running?

Home Assistant OS

### How did you install the stromer integration

HACS

**Comment by CoMPaTech** [comment]
Thanks for reporting @DarthLowen - I've updated that line of code (and refreshed some other requirements) and https://github.com/CoMPaTech/stromer/releases/tag/v0.2.0 should be available and working. Visiting back the forum I guess I should spend some time incorporating `elnkosc`s library to make things easier, but for now this should work.

**Comment by DarthLowen** [comment]
Thanks for the swift action! I can confirm that this specific warning has disappeared. Incorporating `elnkosc`s lib would be awesome, I'd love to plot the location of my bike on the map.

Nogmaals dank en groeten uit BE...
