### ISSUE TITLE
[Legacy Support]: Support Homey integration

### ISSUE THREAD

**Issue by wdool** [CoMPaTech/stromer#112]
### Describe the bug.

Currently I am striving to integrate my bike into smart Home, at least I can run this on HA and sync via MQTT. But better would be to sync this directly via an app into Homey. Any possibilities?

### What version of Home Assistant Core has the issue?

Home Assistant 2023.7.3

### What was the last working version of Home Assistant Core?

Home Assistant 2023.7.3

### What type of installation are you running?

Home Assistant OS

### How did you install the stromer integration

Manually installed `custom_component`

### Logging

no

### Diagnostics information

no

### Additional information

no

**Comment by CoMPaTech** [comment]
See #111
