### ISSUE TITLE
[BUG]: stromer maintenance

### ISSUE THREAD

**Issue by CoMPaTech** [CoMPaTech/stromer#41]
### Describe the bug.

Nice2have - handle Stromer maintenance:
`2023-10-17 11:00:16.285 ERROR (MainThread) [custom_components.stromer.stromer] <ClientResponse(https://api3.stromer-portal.ch/maintenance_static.html) [200 OK]>`

### What version of Home Assistant Core has the issue?

n/a

### What was the last working version of Home Assistant Core?

b/a

### What type of installation are you running?

Home Assistant OS

### How did you install the stromer integration

HACS

**Comment by sammyke007** [comment]
Same here I guess. It stopped working 2 days before updating to 0.2.4. 

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.stromer.stromer
Source: custom_components/stromer/stromer.py:56
Integration: Stromer e-bike (documentation, issues)
First occurred: 00:20:33 (2 occurrences)
Last logged: 10:55:25

Stromer unable to update:

---

Logger: homeassistant.config_entries
Source: config_entries.py:423
First occurred: 00:20:34 (2 occurrences)
Last logged: 10:55:48

Config entry 'ST3 Pinion Sammy' for stromer integration could not authenticate

**Comment by sammyke007** [comment]
Reverting to 0.2.3 works, 0.2.4 doens't...

**Comment by CoMPaTech** [comment]
Deleted pending investigation (tnx!)

**Comment by CoMPaTech** [comment]
Check if #49 fixes this
