### ISSUE TITLE
[BUG]: wrong unit

### ISSUE THREAD

**Issue by Tinus78** [CoMPaTech/stromer#46]
### Describe the bug.

The 'Energy Used' entities both have the unit 'Watt' , I think the correct unit is Watthour (Wh).

### What version of Home Assistant Core has the issue?

2023.10.5

### What type of installation are you running?

Home Assistant OS

### How did you install the stromer integration

HACS

### Logging

NA

### Diagnostics information

NA

### Additional information

NA

**Comment by Tinus78** [comment]
Solution:

In Sensor.py, add ENERGY_WATT_HOUR:

from homeassistant.const import (LENGTH_KILOMETERS, PERCENTAGE, POWER_WATT,
                                 PRESSURE_BAR, SPEED_KILOMETERS_PER_HOUR,
                                 TEMP_CELSIUS, TIME_SECONDS, **ENERGY_WATT_HOUR**)

and change native unit of measurement here:

 SensorEntityDescription(
        key="total_energy_consumption",
        name="Energy used (total)",
        native_unit_of_measurement=ENERGY_WATT_HOUR,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),

and here:

    SensorEntityDescription(
        key="average_energy_consumption",
        name="Energy used (average)",
        native_unit_of_measurement=ENERGY_WATT_HOUR,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),

**Comment by CoMPaTech** [comment]
Needs some more changes: `is using native unit of measurement 'Wh' which is not a valid unit for the device class ('power') it is using; expected one of ['W', 'kW']; `

**Comment by CoMPaTech** [comment]
Fixed in `v0.2.7` although it requires to dump the old data ... other approach would be to introduce new names (and you'd have to manually delete the old ones).
