### ISSUE TITLE
[FEATURE]: Posible to get TTM voltage as a sensor? 

### ISSUE THREAD

**Issue by NikolajChristensen** [CoMPaTech/stromer#51]
### Describe the bug.

Would love to be able to see current TTM voltage in the integration. Is that possible perhaps? 

### What version of Home Assistant Core has the issue?

Latest

### What was the last working version of Home Assistant Core?

Latest

### What type of installation are you running?

Home Assistant OS

### How did you install the stromer integration

HACS

**Comment by CoMPaTech** [comment]
Hi @NikolajChristensen 

Currently the API seems to provide:

ret {'result': 'ok', 'data': [{'nickname': 'S-EVE', 'bikeid': 64279, 'bikemodel': 'ST2', 'biketype': 'ST2-i', 'color': 'white', 'size': 'sport 20', 'hardware': 'omniinterfacec', 'connectivity': 'standard', 'has_crash_detection': True, 'maintenance_feature': {'display_maintenance_event': False, 'next_maintenance_km': 6919, 'next_maintenance_date': '20240711', 'next_maintenance_interval': 3000, 'customer_enabled_maintenance': True, 'last_maintenance_reset_km': 3919, 'last_maintenance_reset_date': '20230711'}}]}
ret {'result': 'not reachable', 'data': [{'trip_distance': 2312.4, 'suiversion': '4.4.1.4', 'average_speed_trip': 36.5, 'average_speed_total': 36.9, 'power_on_cycles': 233, 'tntversion': '5.5', 'atmospheric_pressure': 0, 'battery_SOC': 48, 'assistance_level': 0, 'bike_speed': 0.0, 'trip_time': 227572, 'battery_health': 98, 'theft_flag': False, 'motor_temp': 69.0, 'battery_temp': 43.1, 'rcvts': 1694018537, 'average_energy_consumption': 14, 'total_time': 415676, 'total_distance': 4271.5, 'light_on': 0, 'total_energy_consumption': 61295, 'lock_flag': False}]}
ret {'result': 'not reachable', 'data': [{'latitude': 52.01995, 'longitude': 5.0693, 'altitude': 0, 'speed': 0.334, 'timets': 1694018522, 'rcvts': 1694018537}]}
```json
```

```json
```

**Comment by CoMPaTech** [comment]
Hi @NikolajChristensen 

Currently the API seems to provide the following (assuming you reference TMM?) for my bike: I don't think debug is enabled properly in the current version of the integration to allow you to see this data by simply enabling debugging on the device. 

```json
{'nickname': 'redacted', 'bikeid': 'redacted', 'bikemodel': 'STx', 'biketype': 'STx-y', 'color': 'redacted', 'size': 'redacted', 'hardware': 'omniinterfacec', 'connectivity': 'standard', 'has_crash_detection': True, 'maintenance_feature': {'display_maintenance_event': False, 'next_maintenance_km': 'redacted', 'next_maintenance_date': 'redacted', 'next_maintenance_interval': 3000, 'customer_enabled_maintenance': True, 'last_maintenance_reset_km': 'redacted', 'last_maintenance_reset_date': 'redacted'}}
```

```json
{'latitude': 'redacted', 'longitude': 'redacted', 'altitude': 'redacted', 'speed': 0.334, 'timets': 1790014521, 'rcvts': 1790014533}
```

```json
{'trip_distance': 'redacted', 'suiversion': '4.4.1.4', 'average_speed_trip': 'redacted', 'average_speed_total': 'redacted, 'power_on_cycles': 'redacted', 'tntversion': '5.5', 'atmospheric_pressure': 0, 'battery_SOC': 43, 'assistance_level': 0, 'bike_speed': 0.0, 'trip_time': 'redacted', 'battery_health': 'redacted, 'theft_flag': False, 'motor_temp': 62.0, 'battery_temp': 10.2, 'rcvts': 1704014533, 'average_energy_consumption': 'redacted', 'total_time': 'redacted', 'total_distance': 'redacted', 'light_on': 0, 'total_energy_consumption': 'redacted', 'lock_flag': False}
```

**Comment by CoMPaTech** [comment]
Ah right, if you 'enable' debugging and after a while disable it - you'll get the appropriate logging downloaded containing the JSON data. (http..your-homeassistant-url.../config/integrations/integration/stromer -> debug button)

**Comment by NikolajChristensen** [comment]
Ok. So no TMM voltage. But thanks!

**Comment by CoMPaTech** [comment]
At least not with these calls ... shall we close the issue (for now)?

**Comment by NikolajChristensen** [comment]
Yeah. Thanks for the consideration.
