### ISSUE TITLE
[BUG]: wrong state class being used for _energy_used_average and _energy_used_total?

### ISSUE THREAD

**Issue by sammyke007** [CoMPaTech/stromer#62]
### Describe the bug.

The following error pops up in the HA log:

```
Entity sensor.st3_pinion_sammy_energy_used_average (<class 'custom_components.stromer.sensor.StromerSensor'>) is using state class 'measurement' which is impossible considering device class ('energy') it is using; expected None or one of 'total', 'total_increasing'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/CoMPaTech/stromer/issues
Entity sensor.st3_pinion_sammy_energy_used_total (<class 'custom_components.stromer.sensor.StromerSensor'>) is using state class 'measurement' which is impossible considering device class ('energy') it is using; expected None or one of 'total', 'total_increasing'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/CoMPaTech/stromer/issues
```

### What version of Home Assistant Core has the issue?

2023.12.0

### What was the last working version of Home Assistant Core?

2023.12.0

### What type of installation are you running?

Home Assistant OS

### How did you install the stromer integration

HACS

**Comment by CoMPaTech** [comment]
I'll look into it!

**Comment by sammyke007** [comment]
I've deleted the integration, updated to 0.2.8 and readded my account, but the same error is still there?

**Comment by CoMPaTech** [comment]
I'm trying to test 0.2.9a1 myself on my dev instance first ... if you are anxious to test it, apply the 'show beta' trigger in HACS.

**Comment by CoMPaTech** [comment]
Sry, didn't spot it auto-closing the issue

**Comment by sammyke007** [comment]
0.2.9a1 seems to be OK now over here. I've completely removed the integration, removed LTS from the sensors, reinstalled 0.2.9a1 and the error is gone now.

**Comment by CoMPaTech** [comment]
ok, I'll push it to release than as 0.2.9 - thanks for reporting & testing
